"""
########################################################################
The tables.py module includes the FAOTables Class, which containes 
values for the Parameters.py module as defined in FAO56 tables 11, 12, 
17, and 22. 

The tables.py module contains the following:
    Tables - A class for organizing parameter values defined by FAO56 
              tables. 

12/12/2024 Initial FAOTables class created and defined by Reagan Ames 
and Tyler Pokoski
########################################################################
"""

import pandas as pd


class FAOTables:
    """
    The following assumptions were made to determine the most applicable
    values from the FAO56 tables.
      For tables 12, 17, and 22 -
            Assume left most value in range
            Assume unstressed conditions
                  For fruit trees assume active ground cover and no frosts
                  For Citrus assume 70% canopy cover
                  For tropical trees assume ground cover
                  For Tea assume unshaded conditions
            For forages assume “individual cutting period” for basic value
            Assume sweet maize is harvested fresh for human consumption
            Assume field maize is allowed to dry before harvest
            Beans, legumes, tomatoes, peppers, and cucumbers do not reach a
            height greater than 1.5 to 2m in height
            For oil crops, assume higher value coorelated with rainfed crops
            Wheat is not hand harvested
        For table 11 -
            Prioritize values based on climate in the following order:
                    Continental Climates
                    Central USA
                    35-45 degree latitude
                    Texas
                    Idaho
                    Arizona
                    California
                    California, Desert
                    Hawaii
                    Semi Arid
                    Arid
                    Europe
                    Mediterranean
                    Mediterranean & Arid
                    Italy
                    Warm Winter
                    West Africa
                    Near East (desert)
                    Tropical Regions
                    High Latitudes
            Second default by planting date (after defaulting climates)
                  Spring before fall
            Assume crucifer values for Brussel sprouts
            For any ranges, assume leftmost value
            Assume 1st year of growth for artichokes
            Sweet Maize is harvested fresh
            Assume alfalfa and sudan have already been harvested once
            (other cutting cycles)
            Sugar cane is ratoon
            For any of the following crops not included in table 11, default
            growth stage values to Field Maize:
                      Garlic
                      Parsnip
                      Turnip (and Rutabaga)
                      Chickpea
                      Garbanzo
                      Mint
                      Strawberries
                      Rapeseed, Canola
                      Clover hay, Berseem
                      Rye Grass Hay
                      Grazing Pasture
                      Turf Grass
                      Cacao
                      Coffee
                      Date Palms
                      Palm Trees
                      Rubber Trees
                      Tea
                      Berries (bushes)
                      Almonds
                      Avocado
                      Conifer Trees
                      Kiwi

    """

    def __init__(self):

        self.tables = {
            "broccoli": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.4,
                "p": 0.45,
            },
            "crucifers": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.4,
                "p": 0.45,
            },
            "cabbage": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.5,
                "p": 0.45,
            },
            "carrots": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.5,
                "p": 0.35,
            },
            "cauliflower": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.4,
                "p": 0.45,
            },
            "celery": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 1.0,
                "h": 0.6,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.9,
                "Zrmax": 0.3,
                "p": 0.2,
            },
            "garlic": {
                "Kcini": 0.7,
                "Kcmid": 1,
                "Kcend": 0.7,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.6,
                "Zrmax": 0.3,
                "p": 0.3,
            },
            "lettuce": {
                "Kcini": 0.7,
                "Kcmid": 1,
                "Kcend": 0.95,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.9,
                "Zrmax": 0.3,
                "p": 0.3,
            },
            "onions (dry)": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.75,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.65,
                "Zrmax": 0.3,
                "p": 0.3,
            },
            "onions (green)": {
                "Kcini": 0.7,
                "Kcmid": 1,
                "Kcend": 1.0,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.9,
                "Zrmax": 0.3,
                "p": 0.3,
            },
            "onions (seed)": {
                "Kcini": 0.7,
                "Kcmid": 1.05,
                "Kcend": 0.8,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.7,
                "Zrmax": 0.3,
                "p": 0.35,
            },
            "spinach": {
                "Kcini": 0.7,
                "Kcmid": 1,
                "Kcend": 0.95,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.85,
                "Zrmax": 0.3,
                "p": 0.2,
            },
            "radish": {
                "Kcini": 0.7,
                "Kcmid": 0.9,
                "Kcend": 0.85,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.85,
                "Kcbend": 0.75,
                "Zrmax": 0.3,
                "p": 0.3,
            },
            "egg plant": {
                "Kcini": 0.6,
                "Kcmid": 1.05,
                "Kcend": 0.9,
                "h": 0.8,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.8,
                "Zrmax": 0.7,
                "p": 0.45,
            },
            "sweet peppers (bell)": {
                "Kcini": 0.6,
                "Kcmid": 1.05,
                "Kcend": 0.9,
                "h": 0.7,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.8,
                "Zrmax": 0.5,
                "p": 0.3,
            },
            "tomato": {
                "Kcini": 0.6,
                "Kcmid": 1.15,
                "Kcend": 0.7,
                "h": 0.6,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.6,
                "Zrmax": 0.7,
                "p": 0.4,
            },
            "cantaloupe": {
                "Kcini": 0.5,
                "Kcmid": 0.85,
                "Kcend": 0.6,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.75,
                "Kcbend": 0.5,
                "Zrmax": 0.9,
                "p": 0.45,
            },
            "cucumber (fresh market)": {
                "Kcini": 0.6,
                "Kcmid": 1,
                "Kcend": 0.75,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.7,
                "Zrmax": 0.7,
                "p": 0.5,
            },
            "cucumber (machine harvest)": {
                "Kcini": 0.5,
                "Kcmid": 1,
                "Kcend": 0.9,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.8,
                "Zrmax": 0.7,
                "p": 0.5,
            },
            "pumpkin, winter squash": {
                "Kcini": 0.5,
                "Kcmid": 1,
                "Kcend": 0.8,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.7,
                "Zrmax": 1.0,
                "p": 0.35,
            },
            "squash, zucchini": {
                "Kcini": 0.5,
                "Kcmid": 0.95,
                "Kcend": 0.75,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.7,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "sweet melons": {
                "Kcini": 0.5,
                "Kcmid": 1.05,
                "Kcend": 0.75,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.7,
                "Zrmax": 0.8,
                "p": 0.4,
            },
            "watermelon": {
                "Kcini": 0.4,
                "Kcmid": 1,
                "Kcend": 0.75,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.7,
                "Zrmax": 0.8,
                "p": 0.4,
            },
            "beets, table": {
                "Kcini": 0.5,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "cassava (year 1)": {
                "Kcini": 0.3,
                "Kcmid": 0.8,
                "Kcend": 0.3,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 0.7,
                "Kcbend": 0.2,
                "Zrmax": 0.5,
                "p": 0.35,
            },
            "cassava (year 2)": {
                "Kcini": 0.3,
                "Kcmid": 1.1,
                "Kcend": 0.5,
                "h": 1.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.45,
                "Zrmax": 0.7,
                "p": 0.4,
            },
            "parsnip": {
                "Kcini": 0.5,
                "Kcmid": 1.05,
                "Kcend": 0.95,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.85,
                "Zrmax": 0.5,
                "p": 0.4,
            },
            "potato": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 0.75,
                "h": 0.6,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.65,
                "Zrmax": 0.4,
                "p": 0.35,
            },
            "sweet potato": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 0.65,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.55,
                "Zrmax": 1.0,
                "p": 0.65,
            },
            "turnip (and rutabaga)": {
                "Kcini": 0.5,
                "Kcmid": 1.1,
                "Kcend": 0.95,
                "h": 0.6,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.85,
                "Zrmax": 0.5,
                "p": 0.5,
            },
            "sugar beet": {
                "Kcini": 0.35,
                "Kcmid": 1.2,
                "Kcend": 0.7,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.15,
                "Kcbend": 0.5,
                "Zrmax": 0.7,
                "p": 0.55,
            },
            "beans, green": {
                "Kcini": 0.5,
                "Kcmid": 1.05,
                "Kcend": 0.9,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.8,
                "Zrmax": 0.5,
                "p": 0.45,
            },
            "beans, dry and pulses": {
                "Kcini": 0.4,
                "Kcmid": 1.15,
                "Kcend": 0.35,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.25,
                "Zrmax": 0.6,
                "p": 0.45,
            },
            "chick pea": {
                "Kcini": 0.4,
                "Kcmid": 1,
                "Kcend": 0.35,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.25,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "fababean (fresh)": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 1.1,
                "h": 0.8,
                "Kcbini": 0.15,
                "Kcbmid": 1.10,
                "Kcbend": 1.05,
                "Zrmax": 0.5,
                "p": 0.45,
            },
            "fababean (dry)": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 0.3,
                "h": 0.8,
                "Kcbini": 0.15,
                "Kcbmid": 1.10,
                "Kcbend": 0.2,
                "Zrmax": 0.5,
                "p": 0.45,
            },
            "garbanzo": {
                "Kcini": 0.4,
                "Kcmid": 1.15,
                "Kcend": 0.35,
                "h": 0.8,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.25,
                "Zrmax": 0.6,
                "p": 0.45,
            },
            "green gram and cowpeas (fresh)": {
                "Kcini": 0.4,
                "Kcmid": 1.05,
                "Kcend": 0.6,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.55,
                "Zrmax": 0.6,
                "p": 0.45,
            },
            "green gram and cowpeas (dry)": {
                "Kcini": 0.4,
                "Kcmid": 1.05,
                "Kcend": 0.35,
                "h": 1.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.25,
                "Zrmax": 0.6,
                "p": 0.45,
            },
            "groundnut (peanut)": {
                "Kcini": 0.4,
                "Kcmid": 1.15,
                "Kcend": 0.6,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.5,
                "Zrmax": 0.5,
                "p": 0.5,
            },
            "lentil": {
                "Kcini": 0.4,
                "Kcmid": 1.1,
                "Kcend": 0.3,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.2,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "peas (fresh)": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 1.1,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 1.05,
                "Zrmax": 0.6,
                "p": 0.35,
            },
            "peas (dry)": {
                "Kcini": 0.5,
                "Kcmid": 1.15,
                "Kcend": 0.3,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.2,
                "Zrmax": 0.6,
                "p": 0.4,
            },
            "soybeans": {
                "Kcini": 0.4,
                "Kcmid": 1.15,
                "Kcend": 0.5,
                "h": 0.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.3,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "artichokes": {
                "Kcini": 0.5,
                "Kcmid": 1,
                "Kcend": 0.95,
                "h": 0.7,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.9,
                "Zrmax": 0.6,
                "p": 0.45,
            },
            "asparagus": {
                "Kcini": 0.5,
                "Kcmid": 0.95,
                "Kcend": 0.3,
                "h": 0.2,
                "Kcbini": 0.15,
                "Kcbmid": 0.9,
                "Kcbend": 0.2,
                "Zrmax": 1.2,
                "p": 0.45,
            },
            "mint": {
                "Kcini": 0.6,
                "Kcmid": 1.15,
                "Kcend": 1.1,
                "h": 0.6,
                "Kcbini": 0.4,
                "Kcbmid": 1.1,
                "Kcbend": 1.05,
                "Zrmax": 0.4,
                "p": 0.4,
            },
            "strawberries": {
                "Kcini": 0.4,
                "Kcmid": 0.85,
                "Kcend": 0.75,
                "h": 0.2,
                "Kcbini": 0.3,
                "Kcbmid": 0.8,
                "Kcbend": 0.7,
                "Zrmax": 0.2,
                "p": 0.2,
            },
            "cotton": {
                "Kcini": 0.35,
                "Kcmid": 1.15,
                "Kcend": 0.7,
                "h": 1.2,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.5,
                "Zrmax": 1.0,
                "p": 0.65,
            },
            "flax": {
                "Kcini": 0.35,
                "Kcmid": 1.1,
                "Kcend": 0.25,
                "h": 1.2,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.2,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "sisal": {
                "Kcini": 0.35,
                "Kcmid": 0.4,
                "Kcend": 0.4,
                "h": 1.5,
                "Kcbini": 0.15,
                "Kcbmid": 0.4,
                "Kcbend": 0.4,
                "Zrmax": 0.5,
                "p": 0.8,
            },
            "castorbean (ricinus)": {
                "Kcini": 0.35,
                "Kcmid": 1.15,
                "Kcend": 0.55,
                "h": 0.3,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.45,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "rapeseed, canola": {
                "Kcini": 0.35,
                "Kcmid": 1.15,
                "Kcend": 0.35,
                "h": 0.6,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.25,
                "Zrmax": 1.0,
                "p": 0.6,
            },
            "safflower": {
                "Kcini": 0.35,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 0.8,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.2,
                "Zrmax": 1.0,
                "p": 0.6,
            },
            "sesame": {
                "Kcini": 0.35,
                "Kcmid": 1.1,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.2,
                "Zrmax": 1.0,
                "p": 0.6,
            },
            "sunflower": {
                "Kcini": 0.35,
                "Kcmid": 1.15,
                "Kcend": 0.35,
                "h": 2.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.25,
                "Zrmax": 0.8,
                "p": 0.45,
            },
            "barley": {
                "Kcini": 0.3,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.15,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "oats": {
                "Kcini": 0.3,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.15,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "spring wheat": {
                "Kcini": 0.3,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.15,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "winter wheat (frozen soils)": {
                "Kcini": 0.4,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.15,
                "Zrmax": 1.5,
                "p": 0.55,
            },
            "winter wheat (non - frozen soils)": {
                "Kcini": 0.7,
                "Kcmid": 1.15,
                "Kcend": 0.25,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 0.15,
                "Zrmax": 1.5,
                "p": 0.55,
            },
            "maize, field (grain)": {
                "Kcini": 0.3,
                "Kcmid": 1.2,
                "Kcend": 0.6,
                "h": 2.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.15,
                "Kcbend": 0.5,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "maize, sweet (sweet corn)": {
                "Kcini": 0.3,
                "Kcmid": 1.15,
                "Kcend": 1.05,
                "h": 1.5,
                "Kcbini": 0.15,
                "Kcbmid": 1.1,
                "Kcbend": 1.0,
                "Zrmax": 0.8,
                "p": 0.5,
            },
            "millet": {
                "Kcini": 0.3,
                "Kcmid": 1,
                "Kcend": 0.3,
                "h": 1.5,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.2,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "sorghum (grain)": {
                "Kcini": 0.3,
                "Kcmid": 1,
                "Kcend": 0.55,
                "h": 1.0,
                "Kcbini": 0.15,
                "Kcbmid": 0.95,
                "Kcbend": 0.35,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "sorghum (sweet)": {
                "Kcini": 0.3,
                "Kcmid": 1.2,
                "Kcend": 1.05,
                "h": 2.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.15,
                "Kcbend": 1.0,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "rice": {
                "Kcini": 1.05,
                "Kcmid": 1.2,
                "Kcend": 0.9,
                "h": 1.0,
                "Kcbini": 1.0,
                "Kcbmid": 1.15,
                "Kcbend": 0.7,
                "Zrmax": 0.5,
                "p": 0.2,
            },
            "alfalfa hay": {
                "Kcini": 0.4,
                "Kcmid": 0.95,
                "Kcend": 0.9,
                "h": 0.7,
                "Kcbini": 0.3,
                "Kcbmid": 1.15,
                "Kcbend": 1.1,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "alfalfa hay (seed)": {
                "Kcini": 0.4,
                "Kcmid": 0.5,
                "Kcend": 0.5,
                "h": 0.7,
                "Kcbini": 0.3,
                "Kcbmid": 0.45,
                "Kcbend": 0.45,
                "Zrmax": 1.0,
                "p": 0.6,
            },
            "bermuda hay": {
                "Kcini": 0.55,
                "Kcmid": 1.00,
                "Kcend": 0.85,
                "h": 0.35,
                "Kcbini": 0.5,
                "Kcbmid": 0.95,
                "Kcbend": 0.8,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "bermuda hay (seed)": {
                "Kcini": 0.35,
                "Kcmid": 0.9,
                "Kcend": 0.65,
                "h": 0.4,
                "Kcbini": 0.15,
                "Kcbmid": 0.85,
                "Kcbend": 0.6,
                "Zrmax": 1.0,
                "p": 0.6,
            },
            "clover hay, berseem": {
                "Kcini": 0.4,
                "Kcmid": 0.90,
                "Kcend": 0.85,
                "h": 0.6,
                "Kcbini": 0.3,
                "Kcbmid": 1.1,
                "Kcbend": 1.05,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "rye grass hay": {
                "Kcini": 0.95,
                "Kcmid": 1.05,
                "Kcend": 1.0,
                "h": 0.3,
                "Kcbini": 0.85,
                "Kcbmid": 1.0,
                "Kcbend": 0.95,
                "Zrmax": 0.6,
                "p": 0.6,
            },
            "sudan grass hay (annual)": {
                "Kcini": 0.5,
                "Kcmid": 0.90,
                "Kcend": 0.85,
                "h": 1.2,
                "Kcbini": 0.3,
                "Kcbmid": 1.1,
                "Kcbend": 1.05,
                "Zrmax": 1.0,
                "p": 0.55,
            },
            "grazing pasture (rotated)": {
                "Kcini": 0.4,
                "Kcmid": 0.85,
                "Kcend": 0.85,
                "h": 0.15,
                "Kcbini": 0.3,
                "Kcbmid": 0.8,
                "Kcbend": 0.8,
                "Zrmax": 0.5,
                "p": 0.6,
            },
            "grazing pasture": {
                "Kcini": 0.3,
                "Kcmid": 0.75,
                "Kcend": 0.75,
                "h": 0.1,
                "Kcbini": 0.3,
                "Kcbmid": 0.7,
                "Kcbend": 0.7,
                "Zrmax": 0.5,
                "p": 0.6,
            },
            "turf grass (cool season)": {
                "Kcini": 0.9,
                "Kcmid": 0.95,
                "Kcend": 0.95,
                "h": 0.1,
                "Kcbini": 0.85,
                "Kcbmid": 0.9,
                "Kcbend": 0.9,
                "Zrmax": 0.5,
                "p": 0.4,
            },
            "turf grass (warm season)": {
                "Kcini": 0.8,
                "Kcmid": 0.85,
                "Kcend": 0.85,
                "h": 0.1,
                "Kcbini": 0.75,
                "Kcbmid": 0.8,
                "Kcbend": 0.8,
                "Zrmax": 0.5,
                "p": 0.5,
            },
            "sugar cane": {
                "Kcini": 0.4,
                "Kcmid": 1.25,
                "Kcend": 0.75,
                "h": 3.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.2,
                "Kcbend": 0.7,
                "Zrmax": 1.2,
                "p": 0.65,
            },
            "banana (1st year)": {
                "Kcini": 0.5,
                "Kcmid": 1.1,
                "Kcend": 1.0,
                "h": 3.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.05,
                "Kcbend": 0.9,
                "Zrmax": 0.5,
                "p": 0.35,
            },
            "banana (2nd year)": {
                "Kcini": 1.0,
                "Kcmid": 1.2,
                "Kcend": 1.1,
                "h": 4.0,
                "Kcbini": 0.6,
                "Kcbmid": 1.1,
                "Kcbend": 1.05,
                "Zrmax": 0.5,
                "p": 0.35,
            },
            "cacao": {
                "Kcini": 1.0,
                "Kcmid": 1.05,
                "Kcend": 1.05,
                "h": 3.0,
                "Kcbini": 0.9,
                "Kcbmid": 1.0,
                "Kcbend": 1.0,
                "Zrmax": 0.7,
                "p": 0.3,
            },
            "coffee": {
                "Kcini": 1.05,
                "Kcmid": 1.1,
                "Kcend": 1.1,
                "h": 2.0,
                "Kcbini": 1.0,
                "Kcbmid": 1.05,
                "Kcbend": 1.05,
                "Zrmax": 0.9,
                "p": 0.4,
            },
            "date palms": {
                "Kcini": 0.9,
                "Kcmid": 0.95,
                "Kcend": 0.95,
                "h": 8.0,
                "Kcbini": 0.8,
                "Kcbmid": 0.85,
                "Kcbend": 0.85,
                "Zrmax": 1.5,
                "p": 0.5,
            },
            "palm trees": {
                "Kcini": 0.95,
                "Kcmid": 1,
                "Kcend": 1.0,
                "h": 8.0,
                "Kcbini": 0.85,
                "Kcbmid": 0.9,
                "Kcbend": 0.9,
                "Zrmax": 0.7,
                "p": 0.65,
            },
            "pineapple": {
                "Kcini": 0.5,
                "Kcmid": 0.5,
                "Kcend": 0.5,
                "h": 0.6,
                "Kcbini": 0.3,
                "Kcbmid": 0.45,
                "Kcbend": 0.45,
                "Zrmax": 0.3,
                "p": 0.5,
            },
            "rubber trees": {
                "Kcini": 0.95,
                "Kcmid": 1,
                "Kcend": 1.0,
                "h": 10.0,
                "Kcbini": 0.85,
                "Kcbmid": 0.9,
                "Kcbend": 0.9,
                "Zrmax": 1.0,
                "p": 0.4,
            },
            "tea": {
                "Kcini": 0.95,
                "Kcmid": 1,
                "Kcend": 1.0,
                "h": 1.5,
                "Kcbini": 0.9,
                "Kcbmid": 0.95,
                "Kcbend": 0.9,
                "Zrmax": 0.9,
                "p": 0.4,
            },
            "berries (bushes)": {
                "Kcini": 0.3,
                "Kcmid": 1.05,
                "Kcend": 0.5,
                "h": 1.5,
                "Kcbini": 0.2,
                "Kcbmid": 1.0,
                "Kcbend": 0.4,
                "Zrmax": 0.6,
                "p": 0.5,
            },
            "grapes (table or raisin)": {
                "Kcini": 0.3,
                "Kcmid": 0.85,
                "Kcend": 0.45,
                "h": 2.0,
                "Kcbini": 0.15,
                "Kcbmid": 0.8,
                "Kcbend": 0.4,
                "Zrmax": 1.0,
                "p": 0.35,
            },
            "grapes (wine)": {
                "Kcini": 0.3,
                "Kcmid": 0.7,
                "Kcend": 0.45,
                "h": 1.5,
                "Kcbini": 0.15,
                "Kcbmid": 0.65,
                "Kcbend": 0.4,
                "Zrmax": 1.0,
                "p": 0.45,
            },
            "hops": {
                "Kcini": 0.3,
                "Kcmid": 1.05,
                "Kcend": 0.85,
                "h": 5.0,
                "Kcbini": 0.15,
                "Kcbmid": 1.0,
                "Kcbend": 0.8,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "almonds": {
                "Kcini": 0.4,
                "Kcmid": 0.9,
                "Kcend": 0.65,
                "h": 5.0,
                "Kcbini": 0.2,
                "Kcbmid": 0.85,
                "Kcbend": 0.6,
                "Zrmax": 1.0,
                "p": 0.4,
            },
            "apples, cherries, pears": {
                "Kcini": 0.8,
                "Kcmid": 1.2,
                "Kcend": 0.85,
                "h": 4.0,
                "Kcbini": 0.75,
                "Kcbmid": 1.15,
                "Kcbend": 0.8,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "apricots, peaches, stone fruit": {
                "Kcini": 0.8,
                "Kcmid": 1.15,
                "Kcend": 0.85,
                "h": 3.0,
                "Kcbini": 0.75,
                "Kcbmid": 1.1,
                "Kcbend": 0.8,
                "Zrmax": 1.0,
                "p": 0.5,
            },
            "avocado": {
                "Kcini": 0.6,
                "Kcmid": 0.85,
                "Kcend": 0.75,
                "h": 3.0,
                "Kcbini": 0.5,
                "Kcbmid": 0.8,
                "Kcbend": 0.7,
                "Zrmax": 0.5,
                "p": 0.7,
            },
            "citrus": {
                "Kcini": 0.75,
                "Kcmid": 0.7,
                "Kcend": 0.75,
                "h": 4.0,
                "Kcbini": 0.75,
                "Kcbmid": 0.7,
                "Kcbend": 0.75,
                "Zrmax": 1.2,
                "p": 0.5,
            },
            "conifer trees": {
                "Kcini": 1.0,
                "Kcmid": 1,
                "Kcend": 1.0,
                "h": 10.0,
                "Kcbini": 0.95,
                "Kcbmid": 0.95,
                "Kcbend": 0.95,
                "Zrmax": 1.0,
                "p": 0.7,
            },
            "kiwi": {
                "Kcini": 0.4,
                "Kcmid": 1.05,
                "Kcend": 1.05,
                "h": 3.0,
                "Kcbini": 0.2,
                "Kcbmid": 1.0,
                "Kcbend": 1.0,
                "Zrmax": 0.7,
                "p": 0.35,
            },
            "olives": {
                "Kcini": 0.65,
                "Kcmid": 0.7,
                "Kcend": 0.7,
                "h": 3.0,
                "Kcbini": 0.55,
                "Kcbmid": 0.65,
                "Kcbend": 0.65,
                "Zrmax": 1.2,
                "p": 0.65,
            },
            "pistachios": {
                "Kcini": 0.4,
                "Kcmid": 1.1,
                "Kcend": 0.45,
                "h": 3.0,
                "Kcbini": 0.2,
                "Kcbmid": 1.05,
                "Kcbend": 0.4,
                "Zrmax": 1.0,
                "p": 0.4,
            },
            "walnut orchard": {
                "Kcini": 0.5,
                "Kcmid": 1.1,
                "Kcend": 0.65,
                "h": 4.0,
                "Kcbini": 0.4,
                "Kcbmid": 1.05,
                "Kcbend": 0.6,
                "Zrmax": 1.7,
                "p": 0.5,
            },
        }
        self.table11 = {
            "broccoli": {
                "Lini": 35,
                "Ldev": 45,
                "Lmid": 40,
                "Llate": 15,
                "Total": 135,
            },
            "crucifers": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 20,
                "Llate": 10,
                "Total": 80,
            },
            "cabbage": {
                "Lini": 40,
                "Ldev": 60,
                "Lmid": 50,
                "Llate": 15,
                "Total": 165,
            },
            "carrots": {
                "Lini": 30,
                "Ldev": 50,
                "Lmid": 90,
                "Llate": 30,
                "Total": 200,
            },
            "cauliflower": {
                "Lini": 35,
                "Ldev": 50,
                "Lmid": 40,
                "Llate": 15,
                "Total": 140,
            },
            "celery": {
                "Lini": 30,
                "Ldev": 55,
                "Lmid": 105,
                "Llate": 20,
                "Total": 210,
            },
            "lettuce": {
                "Lini": 25,
                "Ldev": 35,
                "Lmid": 30,
                "Llate": 10,
                "Total": 100,
            },
            "onions (dry)": {
                "Lini": 20,
                "Ldev": 35,
                "Lmid": 110,
                "Llate": 45,
                "Total": 210,
            },
            "onions (green)": {
                "Lini": 30,
                "Ldev": 55,
                "Lmid": 55,
                "Llate": 40,
                "Total": 180,
            },
            "onions (seed)": {
                "Lini": 20,
                "Ldev": 45,
                "Lmid": 165,
                "Llate": 45,
                "Total": 275,
            },
            "spinach": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 40,
                "Llate": 10,
                "Total": 100,
            },
            "radish": {
                "Lini": 10,
                "Ldev": 10,
                "Lmid": 15,
                "Llate": 5,
                "Total": 40,
            },
            "egg plant": {
                "Lini": 30,
                "Ldev": 40,
                "Lmid": 40,
                "Llate": 20,
                "Total": 130,
            },
            "sweet peppers (bell)": {
                "Lini": 30,
                "Ldev": 40,
                "Lmid": 110,
                "Llate": 30,
                "Total": 210,
            },
            "tomato": {
                "Lini": 35,
                "Ldev": 40,
                "Lmid": 50,
                "Llate": 30,
                "Total": 155,
            },
            "cantaloupe": {
                "Lini": 30,
                "Ldev": 45,
                "Lmid": 35,
                "Llate": 10,
                "Total": 120,
            },
            "cucumber (fresh market)": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 40,
                "Llate": 15,
                "Total": 105,
            },
            "cucumber (machine harvest)": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 40,
                "Llate": 15,
                "Total": 105,
            },
            "pumpkin, winter squash": {
                "Lini": 25,
                "Ldev": 35,
                "Lmid": 35,
                "Llate": 25,
                "Total": 120,
            },
            "squash, zucchini": {
                "Lini": 25,
                "Ldev": 35,
                "Lmid": 25,
                "Llate": 15,
                "Total": 100,
            },
            "sweet melons": {
                "Lini": 30,
                "Ldev": 30,
                "Lmid": 50,
                "Llate": 30,
                "Total": 140,
            },
            "watermelon": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 30,
                "Llate": 30,
                "Total": 110,
            },
            "beets, table": {
                "Lini": 25,
                "Ldev": 30,
                "Lmid": 25,
                "Llate": 10,
                "Total": 90,
            },
            "cassava (year 1)": {
                "Lini": 20,
                "Ldev": 40,
                "Lmid": 90,
                "Llate": 60,
                "Total": 210,
            },
            "cassava (year 2)": {
                "Lini": 150,
                "Ldev": 40,
                "Lmid": 110,
                "Llate": 60,
                "Total": 360,
            },
            "potato": {
                "Lini": 45,
                "Ldev": 30,
                "Lmid": 70,
                "Llate": 20,
                "Total": 165,
            },
            "sweet potato": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 60,
                "Llate": 40,
                "Total": 150,
            },
            "sugar beet": {
                "Lini": 50,
                "Ldev": 40,
                "Lmid": 50,
                "Llate": 40,
                "Total": 180,
            },
            "beans, green": {
                "Lini": 15,
                "Ldev": 25,
                "Lmid": 25,
                "Llate": 10,
                "Total": 75,
            },
            "beans, dry and pulses": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 40,
                "Llate": 20,
                "Total": 110,
            },
            "fababean (fresh)": {
                "Lini": 15,
                "Ldev": 25,
                "Lmid": 35,
                "Llate": 15,
                "Total": 90,
            },
            "fababean (dry)": {
                "Lini": 15,
                "Ldev": 25,
                "Lmid": 35,
                "Llate": 15,
                "Total": 90,
            },
            "green gram and cowpeas (fresh)": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 30,
                "Llate": 20,
                "Total": 110,
            },
            "green gram and cowpeas (dry)": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 30,
                "Llate": 20,
                "Total": 110,
            },
            "groundnut (peanut)": {
                "Lini": 35,
                "Ldev": 45,
                "Lmid": 35,
                "Llate": 25,
                "Total": 140,
            },
            "lentil": {
                "Lini": 25,
                "Ldev": 35,
                "Lmid": 70,
                "Llate": 40,
                "Total": 170,
            },
            "peas (fresh)": {
                "Lini": 35,
                "Ldev": 25,
                "Lmid": 30,
                "Llate": 20,
                "Total": 110,
            },
            "peas (dry)": {
                "Lini": 35,
                "Ldev": 25,
                "Lmid": 30,
                "Llate": 20,
                "Total": 110,
            },
            "soybeans": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 60,
                "Llate": 25,
                "Total": 140,
            },
            "artichokes": {
                "Lini": 40,
                "Ldev": 40,
                "Lmid": 250,
                "Llate": 30,
                "Total": 360,
            },
            "asparagus": {
                "Lini": 90,
                "Ldev": 30,
                "Lmid": 200,
                "Llate": 45,
                "Total": 365,
            },
            "cotton": {
                "Lini": 30,
                "Ldev": 50,
                "Lmid": 55,
                "Llate": 45,
                "Total": 180,
            },
            "flax": {
                "Lini": 30,
                "Ldev": 40,
                "Lmid": 100,
                "Llate": 50,
                "Total": 220,
            },
            "castorbean (ricinus)": {
                "Lini": 25,
                "Ldev": 40,
                "Lmid": 65,
                "Llate": 50,
                "Total": 180,
            },
            "safflower": {
                "Lini": 20,
                "Ldev": 35,
                "Lmid": 45,
                "Llate": 25,
                "Total": 125,
            },
            "sesame": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 40,
                "Llate": 20,
                "Total": 100,
            },
            "sunflower": {
                "Lini": 25,
                "Ldev": 35,
                "Lmid": 45,
                "Llate": 25,
                "Total": 130,
            },
            "barley": {
                "Lini": 20,
                "Ldev": 25,
                "Lmid": 60,
                "Llate": 30,
                "Total": 135,
            },
            "oats": {
                "Lini": 20,
                "Ldev": 25,
                "Lmid": 60,
                "Llate": 30,
                "Total": 135,
            },
            "spring wheat": {
                "Lini": 20,
                "Ldev": 25,
                "Lmid": 60,
                "Llate": 30,
                "Total": 135,
            },
            "winter wheat (frozen soils)": {
                "Lini": 160,
                "Ldev": 75,
                "Lmid": 75,
                "Llate": 25,
                "Total": 335,
            },
            "winter wheat (non - frozen soils)": {
                "Lini": 160,
                "Ldev": 75,
                "Lmid": 75,
                "Llate": 25,
                "Total": 335,
            },
            "maize, field (grain)": {
                "Lini": 30,
                "Ldev": 40,
                "Lmid": 50,
                "Llate": 50,
                "Total": 170,
            },
            "maize, sweet (sweet corn)": {
                "Lini": 30,
                "Ldev": 30,
                "Lmid": 30,
                "Llate": 10,
                "Total": 110,
            },
            "millet": {
                "Lini": 20,
                "Ldev": 30,
                "Lmid": 55,
                "Llate": 35,
                "Total": 140,
            },
            "sorghum (grain)": {
                "Lini": 20,
                "Ldev": 25,
                "Lmid": 40,
                "Llate": 30,
                "Total": 130,
            },
            "sorghum (sweet)": {
                "Lini": 20,
                "Ldev": 25,
                "Lmid": 40,
                "Llate": 30,
                "Total": 130,
            },
            "rice": {
                "Lini": 30,
                "Ldev": 30,
                "Lmid": 60,
                "Llate": 30,
                "Total": 150,
            },
            "alfalfa hay": {
                "Lini": 5,
                "Ldev": 20,
                "Lmid": 10,
                "Llate": 10,
                "Total": 45,
            },
            "alfalfa hay (seed)": {
                "Lini": 5,
                "Ldev": 20,
                "Lmid": 10,
                "Llate": 10,
                "Total": 45,
            },
            "bermuda hay": {
                "Lini": 10,
                "Ldev": 15,
                "Lmid": 75,
                "Llate": 35,
                "Total": 135,
            },
            "bermuda hay (seed)": {
                "Lini": 10,
                "Ldev": 25,
                "Lmid": 35,
                "Llate": 35,
                "Total": 105,
            },
            "sudan grass hay (annual)": {
                "Lini": 3,
                "Ldev": 15,
                "Lmid": 12,
                "Llate": 7,
                "Total": 37,
            },
            "sugar cane": {
                "Lini": 35,
                "Ldev": 105,
                "Lmid": 210,
                "Llate": 70,
                "Total": 420,
            },
            "banana (1st year)": {
                "Lini": 120,
                "Ldev": 90,
                "Lmid": 120,
                "Llate": 60,
                "Total": 390,
            },
            "banana (2nd year)": {
                "Lini": 120,
                "Ldev": 60,
                "Lmid": 180,
                "Llate": 5,
                "Total": 365,
            },
            "pineapple": {
                "Lini": 60,
                "Ldev": 120,
                "Lmid": 600,
                "Llate": 10,
                "Total": 790,
            },
            "grapes (table or raisin)": {
                "Lini": 20,
                "Ldev": 50,
                "Lmid": 75,
                "Llate": 60,
                "Total": 205,
            },
            "grapes (wine)": {
                "Lini": 20,
                "Ldev": 50,
                "Lmid": 75,
                "Llate": 60,
                "Total": 205,
            },
            "hops": {
                "Lini": 25,
                "Ldev": 40,
                "Lmid": 80,
                "Llate": 10,
                "Total": 155,
            },
            "apples, cherries, pears": {
                "Lini": 30,
                "Ldev": 50,
                "Lmid": 130,
                "Llate": 30,
                "Total": 240,
            },
            "apricots, peaches, stone fruit": {
                "Lini": 30,
                "Ldev": 50,
                "Lmid": 130,
                "Llate": 30,
                "Total": 240,
            },
            "citrus": {
                "Lini": 60,
                "Ldev": 90,
                "Lmid": 120,
                "Llate": 95,
                "Total": 365,
            },
            "olives": {
                "Lini": 30,
                "Ldev": 90,
                "Lmid": 60,
                "Llate": 90,
                "Total": 270,
            },
            "pistachios": {
                "Lini": 20,
                "Ldev": 60,
                "Lmid": 30,
                "Llate": 40,
                "Total": 150,
            },
            "walnut orchard": {
                "Lini": 20,
                "Ldev": 10,
                "Lmid": 130,
                "Llate": 30,
                "Total": 190,
            },
        }

        self.syn = {
            "corn": [
                "maize, field (grain)",
                "maize, sweet (sweet corn)",
            ],
            "brussel sprouts": ["crucifers"],
            "brussel sprout": ["crucifers"],
            "red cabbage": ["cabbage"],
            "green cabbage": ["cabbage"],
            "purple cabbage": ["cabbage"],
            "savoy cabbage": ["cabbage"],
            "cabbages": ["cabbage"],
            "carrots": ["carrot"],
            "elephant garlic": ["garlic"],
            "wild garlic": ["garlic"],
            "single clove garlic": ["garlic"],
            "romaine lettuce": ["lettuce"],
            "romaine": ["lettuce"],
            "onions": ["onions(dry)", "onions(green)", "onions(seed)"],
            "onion": ["onions(dry)", "onions(green)", "onions(seed)"],
            "red radish": ["radish"],
            "green radish": ["radish"],
            "black radish": ["radish"],
            "oilseed radish": ["radish"],
            "wild radish": ["radish"],
            "daikon": ["radish"],
            "radishes": ["radish"],
            "eggplant": ["egg plant"],
            "garden egg": ["egg plant"],
            "eggplants": ["egg plant"],
            "egg plants": ["egg plant"],
            "sweet pepper": ["sweet peppers (bell)"],
            "sweet peppers": ["sweet peppers (bell)"],
            "bell pepper": ["sweet peppers (bell)"],
            "bell peppers": ["sweet peppers (bell)"],
            "paprika": ["sweet peppers (bell)"],
            "pepper": ["sweet peppers (bell)"],
            "peppers": ["sweet peppers (bell)"],
            "capsicus": ["sweet peppers (bell)"],
            "tomatoes": ["tomato"],
            "true cantaloupe": ["cantaloupe"],
            "european cantaloupe": ["cantaloupe"],
            "american cantaloupe": ["cantaloupe"],
            "cantaloupes": ["cantaloupe"],
            "muskmelon": ["cantaloupe"],
            "rockmelon": ["cantaloupe"],
            "spanspek": ["cantaloupe"],
            "cucumber": [
                "cucumber (fresh market)",
                "cucumber (machine harvest)",
            ],
            "cucumbers": [
                "cucumber (fresh market)",
                "cucumber (machine harvest)",
            ],
            "pumpkin": ["pumpkin, winter squash"],
            "pumpkins": ["pumpkin, winter squash"],
            "winter squash": ["pumpkin, winter squash"],
            "winter squashes": ["pumpkin, winter squash"],
            "kabocha": ["pumpkin, winter squash"],
            "butternut squash": ["pumpkin, winter squash"],
            "spaghetti squash": ["pumpkin, winter squash"],
            "delicata squash": ["pumpkin, winter squash"],
            "acorn squash": ["pumpkin, winter squash"],
            "squash": ["pumpkin, winter squash", "squash, zucchini"],
            "summer squash": ["squash, zucchini"],
            "crookneck squash": ["squash, zucchini"],
            "gem squash": ["squash, zucchini"],
            "pattypan squash": ["squash, zucchini"],
            "straightneck squash": ["squash, zucchini"],
            "zucchini": ["squash, zucchini"],
            "zucchinis": ["squash, zucchini"],
            "kamokamo": ["squash, zucchini"],
            "aehobak": ["squash, zucchini"],
            "tromboncino": ["squash, zucchini"],
            "zucchetta": ["squash, zucchini"],
            "melon": ["sweet melons", "watermelon"],
            "melons": ["sweet melons", "watermelon"],
            "true melon": ["sweet melons"],
            "horned melon": ["sweet melons"],
            "sweet melon": ["sweet melons"],
            "watermelons": ["watermelon"],
            "beets": ["beets, table"],
            "beet": ["beets, table"],
            "table beets": ["beets, table"],
            "table beet": ["beets, table"],
            "beetroot": ["beets, table"],
            "garden beets": ["beets, table"],
            "garden beet": ["beets, table"],
            "dinner beets": ["beets, table"],
            "dinner beet": ["beets, table"],
            "cassava": ["cassava (year 1)", "cassava (year 2)"],
            "parsnips": ["parsnip"],
            "potatoes": ["potato"],
            "spud": ["potato"],
            "sweet potatoes": ["sweet potato"],
            "turnip": ["turnip (and rutabaga)"],
            "turnips": ["turnip (and rutabaga)"],
            "rutabaga": ["turnip (and rutabaga)"],
            "swedish turnip": ["turnip (and rutabaga)"],
            "white turnip": ["turnip (and rutabaga)"],
            "sugarbeet": ["sugar beet"],
            "sugar beets": ["sugar beet"],
            "sugarbeets": ["sugar beet"],
            "green beans": ["beans, green"],
            "greenbeans": ["beans, green"],
            "green bean": ["beans, green"],
            "greenbean": ["beans, green"],
            "bean": [
                "beans, dry and pulses",
                "beans, green",
                "chick pea",
                "fababean (dry)",
                "fababean (fresh)",
                "garbanzo",
            ],
            "beans": [
                "beans, dry and pulses",
                "beans, green",
                "chick pea",
                "fababean (dry)",
                "fababean (fresh)",
                "garbanzo",
            ],
            "dry beans": ["beans, dry and pulses"],
            "dry broad beans": ["beans, dry and pulses"],
            "pulses": ["beans, dry and pulses"],
            "chickpea": ["chick pea"],
            "chickpeas": ["chick pea"],
            "chick peas": ["chick pea"],
            "fababean": ["fababean (fresh)", "fababean (dry)"],
            "garbanzo bean": ["garbanzo"],
            "garbanzo beans": ["garbanzo"],
            "green gram": [
                "green gram and cowpeas (fresh)",
                "green gram and cowpeas (dry)",
            ],
            "cowpea": [
                "green gram and cowpeas (fresh)",
                "green gram and cowpeas (dry)",
            ],
            "cowpeas": [
                "green gram and cowpeas (fresh)",
                "green gram and cowpeas (dry)",
            ],
            "peanut": ["groundnut (peanut)"],
            "peanuts": ["groundnut (peanut)"],
            "groundnut": ["groundnut (peanut)"],
            "groundnuts": ["groundnut (peanut)"],
            "goober": ["groundnut (peanut)"],
            "goober pea": ["groundnut (peanut)"],
            "pindar": ["groundnut (peanut)"],
            "monkey nut": ["groundnut (peanut)"],
            "lentils": ["lentil"],
            "peas": ["peas (fresh)", "peas (dry)"],
            "pea": ["peas (fresh)", "peas (dry)"],
            "soybean": ["soybeans"],
            "soy bean": ["soybeans"],
            "soy beans": ["soybeans"],
            "soya bean": ["soybeans"],
            "artichoke": ["artichokes"],
            "french artichoke": ["artichokes"],
            "globe artichoke": ["artichokes"],
            "green artichoke": ["artichokes"],
            "mentha": ["mint"],
            "strawberry": ["strawberries"],
            "garden strawberry": ["strawberries"],
            "upland cotton": ["cotton"],
            "extra-long staple cotton": ["cotton"],
            "tree cotton": ["cotton"],
            "levant cotton": ["cotton"],
            "common flax": ["flax"],
            "linseed": ["flax"],
            "castorbean": ["castorbean (ricinus)"],
            "castorbeans": ["castorbean (ricinus)"],
            "ricinus": ["castorbean (ricinus)"],
            "castor oil plant": ["castorbean (ricinus)"],
            "rapeseed": ["rapeseed, canola"],
            "canola": ["rapeseed, canola"],
            "rape": ["rapeseed, canola"],
            "oilseed rape": ["rapeseed, canola"],
            "simsim": ["sesame"],
            "benne": ["sesame"],
            "gingelly": ["sesame"],
            "sunflowers": ["sunflower"],
            "common sunflowers": ["sunflower"],
            "common sunflower": ["sunflower"],
            "common oat": ["oats"],
            "common oats": ["oats"],
            "oat": ["oats"],
            "wheat": [
                "spring wheat",
                "winter wheat (frozen soils)",
                "winter wheat (non-frozen soils)",
            ],
            "winter wheat": [
                "winter wheat (frozen soils)",
                "winter wheat (non-frozen soils)",
            ],
            "maize": [
                "maize, field (grain)",
                "maize, sweet (sweet corn)",
            ],
            "corn": [
                "maize, field (grain)",
                "maize, sweet (sweet corn)",
            ],
            "zea mays": [
                "maize, field (grain)",
                "maize, sweet (sweet corn)",
            ],
            "field corn": ["maize, field (grain)"],
            "sweet corn": ["maize, sweet (sweet corn)"],
            "millets": ["millet"],
            "finger millet": ["millet"],
            "pearl millet": ["millet"],
            "little millet": ["millet"],
            "sorghum": ["sorghum (grain)", "sorghum (sweet)"],
            "great millet": ["sorghum (grain)", "sorghum (sweet)"],
            "broomcorn": ["sorghum (grain)", "sorghum (sweet)"],
            "guinea corn": ["sorghum (grain)", "sorghum (sweet)"],
            "durra": ["sorghum (grain)", "sorghum (sweet)"],
            "imphee": ["sorghum (grain)", "sorghum (sweet)"],
            "jowar": ["sorghum (grain)", "sorghum (sweet)"],
            "milo": ["sorghum (grain)", "sorghum (sweet)"],
            "indica rice": ["rice"],
            "japonica rice": ["rice"],
            "alfalfa": ["alfalfa hay", "alfalfa hay (seed)"],
            "lucerene": ["alfalfa hay", "alfalfa hay (seed)"],
            "bermuda": ["bermuda hay", "bermuda hay (seed)"],
            "bermudagrass": ["bermuda hay", "bermuda hay (seed)"],
            "bermuda grass": ["bermuda hay", "bermuda hay (seed)"],
            "clover hay": ["clover hay, berseem"],
            "berseem": ["clover hay, berseem"],
            "berseem clover": ["clover hay, berseem"],
            "egyptian clover": ["clover hay, berseem"],
            "rye grass": ["rye grass hay"],
            "ryegrass": ["rye grass hay"],
            "sudan grass": ["sudan grass hay (annual)"],
            "sudan grass hay": ["sudan grass hay (annual)"],
            "pasture": ["grazing pasture (rotated)", "grazing pasture"],
            "turf grass": [
                "turf grass (cool season)",
                "turf grass (warm season)",
            ],
            "lawn grass": [
                "turf grass (cool season)",
                "turf grass (warm season)",
            ],
            "sugarcane": ["sugar cane"],
            "cane": ["sugar cane"],
            "banana": ["banana (1st year)", "banana (2nd year)"],
            "bananas": ["banana (1st year)", "banana (2nd year)"],
            "cacao tree": ["cacao"],
            "cocoa tree": ["cacao"],
            "cocoa": ["cacao"],
            "arabica coffee": ["coffee"],
            "coffea arabica": ["coffee"],
            "coffee plant": ["coffee"],
            "dates": ["date palms"],
            "date palm": ["date palms"],
            "date": ["date palms"],
            "palms": ["palm trees"],
            "palm tree": ["palm trees"],
            "pineapples": ["pineapple"],
            "ananas": ["pineapple"],
            "rubber tree": ["rubber trees"],
            "rubber plant": ["rubber trees"],
            "sharinga tree": ["rubber trees"],
            "para rubber tree": ["rubber trees"],
            "rubber plants": ["rubber trees"],
            "tea tree": ["tea"],
            "tea plant": ["tea"],
            "tea shrub": ["tea"],
            "tea trees": ["tea"],
            "tea plants": ["tea"],
            "tea shrubs": ["tea"],
            "berries": ["berries (bushes)", "strawberries"],
            "berry": ["berries (bushes)", "strawberries"],
            "berry shrub": ["berries (bushes)"],
            "berry bushes": ["berries (bushes)"],
            "berry bush": ["berries (bushes)"],
            "blueberries": ["berries (bushes)"],
            "blueberry": ["berries (bushes)"],
            "boysenberry": ["berries (bushes)"],
            "elderberry": ["berries (bushes)"],
            "blackberry": ["berries (bushes)"],
            "blackberries": ["berries (bushes)"],
            "raspberry": ["berries (bushes)"],
            "raspberries": ["berries (bushes)"],
            "grapes": ["grapes (table or raisin)", "grapes (wine)"],
            "grape": ["grapes (table or raisin)", "grapes (wine)"],
            "wine grapes": ["grapes (wine)"],
            "table grapes": ["grapes (table or raisin)"],
            "raisin": ["grapes (table or raisin)"],
            "hop": ["hops"],
            "hops plant": ["hops"],
            "almond": ["almonds"],
            "almond tree": ["almonds"],
            "almond trees": ["almonds"],
            "apples": ["apples, cherries, pears"],
            "apple tree": ["apples, cherries, pears"],
            "apple trees": ["apples, cherries, pears"],
            "apple": ["apples, cherries, pears"],
            "cherries": ["apples, cherries, pears"],
            "cherry": ["apples, cherries, pears"],
            "cherry tree": ["apples, cherries, pears"],
            "cherry trees": ["apples, cherries, pears"],
            "pears": ["apples, cherries, pears"],
            "pear tree": ["apples, cherries, pears"],
            "pear": ["apples, cherries, pears"],
            "pear trees": ["apples, cherries, pears"],
            "apricots": ["apricots, peaches, stone fruit"],
            "apricot": ["apricots, peaches, stone fruit"],
            "apricot tree": ["apricots, peaches, stone fruit"],
            "apricot trees": ["apricots, peaches, stone fruit"],
            "peaches": ["apricots, peaches, stone fruit"],
            "peach": ["apricots, peaches, stone fruit"],
            "peach tree": ["apricots, peaches, stone fruit"],
            "peach trees": ["apricots, peaches, stone fruit"],
            "stone fruit": ["apricots, peaches, stone fruit"],
            "stone fruits": ["apricots, peaches, stone fruit"],
            "avocados": ["avocado"],
            "citrus trees": ["citrus"],
            "citrus tree": ["citrus"],
            "oranges": ["citrus"],
            "orange": ["citrus"],
            "orange tree": ["citrus"],
            "orange trees": ["citrus"],
            "grapefruits": ["citrus"],
            "grapefruit": ["citrus"],
            "grapefruit trees": ["citrus"],
            "grapefruit tree": ["citrus"],
            "limes": ["citrus"],
            "lime": ["citrus"],
            "lime tree": ["citrus"],
            "lime trees": ["citrus"],
            "lemon": ["citrus"],
            "lemons": ["citrus"],
            "lemon tree": ["citrus"],
            "lemon trees": ["citrus"],
            "tangerine": ["citrus"],
            "tangerines": ["citrus"],
            "tangerine trees": ["citrus"],
            "tangerine tree": ["citrus"],
            "conifer tree": ["conifer trees"],
            "coniferous trees": ["conifer trees"],
            "coniferous tree": ["conifer trees"],
            "spruce trees": ["conifer trees"],
            "spruce tree": ["conifer trees"],
            "pine trees": ["conifer trees"],
            "pine tree": ["conifer trees"],
            "fir trees": ["conifer trees"],
            "fir tree": ["conifer trees"],
            "kiwis": ["kiwi"],
            "kiwifruit": ["kiwi"],
            "chinease gooseberry": ["kiwi"],
            "chinease gooseberries": ["kiwi"],
            "kiwifruits": ["kiwi"],
            "olive": ["olives"],
            "green olive": ["olives"],
            "black olive": ["olives"],
            "green olives": ["olives"],
            "black olives": ["olives"],
            "olive tree": ["olives"],
            "olive trees": ["olives"],
            "pistachio": ["pistachios"],
            "pistachio tree": ["pistachios"],
            "pistachio trees": ["pistachios"],
            "walnut": ["walnut orchard"],
            "walnuts": ["walnut orchard"],
            "walnut tree": ["walnut orchard"],
            "walnut trees": ["walnut orchard"],
        }
