"""
########################################################################
The tables.py module includes the FAOTables Class, which containes 
values for the Parameters.py module as defined in FAO56 tables 11, 12, 
17, and 22. 

The tables.py module contains the following:
    Tables - A class for organizing parameter values defined by FAO56 
              tables. 

12/12/2024 Initial FAOTables class created and defined by Reagan Ames 
and Tyler Pokoski
########################################################################
"""

import pandas as pd

class FAOTables:
  '''  
  The following assumptions were made to determine the most applicable
  values from the FAO56 tables. 
    For tables 12, 17, and 22 - 
          Assume left most value in range
          Assume unstressed conditions 
                For fruit trees assume active ground cover and no frosts
                For Citrus assume 70% canopy cover
                For tropical trees assume ground cover
                For Tea assume unshaded conditions
          For forages assume “individual cutting period” for basic value
          Assume sweet maize is harvested fresh for human consumption
          Assume field maize is allowed to dry before harvest
          Beans, legumes, tomatoes, peppers, and cucumbers do not reach a
          height greater than 1.5 to 2m in height
          For oil crops, assume higher value coorelated with rainfed crops
          Wheat is not hand harvested
      For table 11 - 
          Prioritize values based on climate in the following order: 
                  Continental Climates
                  Central USA
                  35-45 degree latitude
                  Texas 
                  Idaho 
                  Arizona
                  California
                  California, Desert
                  Hawaii
                  Semi Arid
                  Arid
                  Europe
                  Mediterranean
                  Mediterranean & Arid
                  Italy
                  Warm Winter
                  West Africa
                  Near East (desert)
                  Tropical Regions
                  High Latitudes
          Second default by planting date (after defaulting climates)
                Spring before fall
          Assume crucifer values for Brussel sprouts
          For any ranges, assume leftmost value
          Assume 1st year of growth for artichokes
          Sweet Maize is harvested fresh
          Assume alfalfa and sudan have already been harvested once 
          (other cutting cycles)
          Sugar cane is ratoon
          For any of the following crops not included in table 11, default
          growth stage values to Field Maize:
                    Garlic
                    Parsnip
                    Turnip (and Rutabaga)
                    Chickpea
                    Garbanzo
                    Mint
                    Strawberries
                    Rapeseed, Canola
                    Clover hay, Berseem
                    Rye Grass Hay
                    Grazing Pasture
                    Turf Grass
                    Cacao
                    Coffee
                    Date Palms
                    Palm Trees
                    Rubber Trees
                    Tea
                    Berries (bushes)
                    Almonds
                    Avocado
                    Conifer Trees
                    Kiwi

  ''' 
  def __init__(self):

    self.tables = {
      'Broccoli': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.95, 'h': 0.3,
                   'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.85, 
                   'Zrmax': 0.4, 'p': 0.45},
      'Brussel Sprouts': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.95, 
                          'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 0.95, 
                          'Kcbend': 0.85, 'Zrmax': 0.4, 'p': 0.45}, 
      'Cabbage': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.95, 'h': 0.4,
                  'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.85, 
                  'Zrmax': 0.5, 'p': 0.45}, 
      'Carrots': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.95, 'h': 0.3,
                  'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.85, 
                  'Zrmax': 0.5, 'p': 0.35}, 
      'Cauliflower': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.95,
                      'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 0.95, 
                      'Kcbend': 0.85, 'Zrmax': 0.4, 'p': 0.45}, 
      'Celery': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 1.0, 'h': 0.6,
                 'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.9, 
                 'Zrmax': 0.3, 'p': 0.2}, 
      'Garlic': {'Kcini': 0.7, 'Kcmid': 1, 'Kcend': 0.7, 'h': 0.3, 
                 'Kcbini': 0.15, 'Kcbmid': 0.9, 'Kcbend': 0.6, 
                 'Zrmax': 0.3, 'p': 0.3}, 
      'Lettuce': {'Kcini': 0.7, 'Kcmid': 1, 'Kcend': 0.95, 'h': 0.3,
                  'Kcbini': 0.15, 'Kcbmid': 0.9, 'Kcbend': 0.9, 
                  'Zrmax': 0.3, 'p': 0.3}, 
      'Onions (dry)': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.75,
                       'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 0.95, 
                       'Kcbend': 0.65, 'Zrmax': 0.3, 'p': 0.3},
      'Onions (green)': {'Kcini': 0.7, 'Kcmid': 1, 'Kcend': 1.0, 
                         'h': 0.3, 'Kcbini': 0.15, 'Kcbmid': 0.9, 
                         'Kcbend': 0.9, 'Zrmax': 0.3, 'p': 0.3}, 
      'Onions (seed)': {'Kcini': 0.7, 'Kcmid': 1.05, 'Kcend': 0.8,
                        'h': 0.5, 'Kcbini': 0.15, 'Kcbmid': 1.05, 
                        'Kcbend': 0.7, 'Zrmax': 0.3, 'p': 0.35},
      'Spinach': {'Kcini': 0.7, 'Kcmid': 1, 'Kcend': 0.95, 'h': 0.3,
                  'Kcbini': 0.15, 'Kcbmid': 0.9, 'Kcbend': 0.85, 
                  'Zrmax': 0.3, 'p': 0.2}, 
      'Radish': {'Kcini': 0.7, 'Kcmid': 0.9, 'Kcend': 0.85, 'h': 0.3,
                 'Kcbini': 0.15, 'Kcbmid': 0.85, 'Kcbend': 0.75, 
                 'Zrmax': 0.3, 'p': 0.3}, 
      'Egg Plant': {'Kcini': 0.6, 'Kcmid': 1.05, 'Kcend': 0.9, 
                    'h': 0.8, 'Kcbini': 0.15, 'Kcbmid': 1.0, 
                    'Kcbend': 0.8, 'Zrmax': 0.7, 'p': 0.45}, 
      'Sweet Peppers (bell)': {'Kcini': 0.6, 'Kcmid': 1.05,
                               'Kcend': 0.9, 'h': 0.7, 'Kcbini': 0.15, 
                               'Kcbmid': 1.0, 'Kcbend': 0.8, 
                               'Zrmax': 0.5, 'p': 0.3}, 
      'Tomato': {'Kcini': 0.6, 'Kcmid': 1.15, 'Kcend': 0.7, 'h': 0.6,
                 'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.6, 
                 'Zrmax': 0.7, 'p': 0.4}, 
      'Cantaloupe': {'Kcini': 0.5, 'Kcmid': 0.85, 'Kcend': 0.6, 
                     'h': 0.3, 'Kcbini': 0.15, 'Kcbmid': 0.75, 
                     'Kcbend': 0.5, 'Zrmax': 0.9, 'p': 0.45}, 
      'Cucumber (Fresh Market)': {'Kcini': 0.6, 'Kcmid': 1, 
                                  'Kcend': 0.75, 'h': 0.3, 
                                  'Kcbini': 0.15, 'Kcbmid': 0.95, 
                                  'Kcbend': 0.7, 'Zrmax': 0.7, 
                                  'p': 0.5}, 
      'Cucumber (Machine Harvest)': {'Kcini': 0.5, 'Kcmid': 1, 
                                     'Kcend': 0.9, 'h': 0.3, 
                                     'Kcbini': 0.15, 'Kcbmid': 0.95, 
                                     'Kcbend': 0.8, 'Zrmax': 0.7, 
                                     'p': 0.5}, 
      'Pumpkin, Winter Squash': {'Kcini': 0.5, 'Kcmid': 1, 'Kcend': 0.8,
                                 'h': 0.4, 'Kcbini': 0.15, 
                                 'Kcbmid': 0.95, 'Kcbend': 0.7, 
                                 'Zrmax': 1.0, 'p': 0.35}, 
      'Squash, Zucchini': {'Kcini': 0.5, 'Kcmid': 0.95, 'Kcend': 0.75,
                           'h': 0.3, 'Kcbini': 0.15, 'Kcbmid': 0.9, 
                           'Kcbend': 0.7, 'Zrmax': 0.6, 'p': 0.5}, 
      'Sweet Melons': {'Kcini': 0.5, 'Kcmid': 1.05, 'Kcend': 0.75,
                       'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 1.0, 
                       'Kcbend': 0.7, 'Zrmax': 0.8, 'p': 0.4}, 
      'Watermelon': {'Kcini': 0.4, 'Kcmid': 1, 'Kcend': 0.75, 'h': 0.4, 
                     'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.7, 
                     'Zrmax': 0.8, 'p': 0.4}, 
      'Beets, table':{'Kcini': 0.5, 'Kcmid': 1.05, 'Kcend': 0.95,
                      'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 0.95, 
                      'Kcbend': 0.85, 'Zrmax': 0.6, 'p': 0.5}, 
      'Cassava (year 1)': {'Kcini': 0.3, 'Kcmid': 0.8, 'Kcend': 0.3,
                           'h': 1.0, 'Kcbini': 0.15, 'Kcbmid': 0.7, 
                           'Kcbend': 0.2, 'Zrmax': 0.5, 'p': 0.35}, 
      'Cassava (year 2)': {'Kcini': 0.3, 'Kcmid': 1.1, 'Kcend': 0.5,
                           'h': 1.5, 'Kcbini': 0.15, 'Kcbmid': 1.0, 
                           'Kcbend': 0.45, 'Zrmax': 0.7, 'p': 0.4}, 
      'Parsnip': {'Kcini': 0.5, 'Kcmid': 1.05, 'Kcend': 0.95, 'h': 0.4,
                  'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.85, 
                  'Zrmax': 0.5, 'p': 0.4}, 
      'Potato': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 0.75, 'h': 0.6, 
                 'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.65, 
                 'Zrmax': 0.4, 'p': 0.35}, 
      'Sweet Potato': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 0.65, 
                       'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                       'Kcbend': 0.55, 'Zrmax': 1.0, 'p': 0.65}, 
      'Turnip (and Rutabaga)': {'Kcini': 0.5, 'Kcmid': 1.1,
                                'Kcend': 0.95, 'h': 0.6,'Kcbini': 0.15, 
                                'Kcbmid': 1.0, 'Kcbend': 0.85, 
                                'Zrmax': 0.5, 'p': 0.5}, 
      'Sugar Beet': {'Kcini': 0.35, 'Kcmid': 1.2, 'Kcend': 0.7, 
                     'h': 0.5, 'Kcbini': 0.15, 'Kcbmid': 1.15, 
                     'Kcbend': 0.5, 'Zrmax': 0.7, 'p': 0.55}, 
      'Beans, green': {'Kcini': 0.5, 'Kcmid': 1.05, 'Kcend': 0.9, 
                       'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 1.0,
                       'Kcbend': 0.8, 'Zrmax': 0.5, 'p': 0.45}, 
      'Beans, dry and Pulses': {'Kcini': 0.4, 'Kcmid': 1.15,
                                'Kcend': 0.35, 'h': 0.4, 'Kcbini': 0.15, 
                                'Kcbmid': 1.1, 'Kcbend': 0.25, 
                                'Zrmax': 0.6, 'p': 0.45}, 
      'Chick pea': {'Kcini': 0.4, 'Kcmid': 1, 'Kcend': 0.35, 'h': 0.4,
                    'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.25, 
                    'Zrmax': 0.6, 'p': 0.5}, 
      'Fababean (Fresh)': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 1.1, 
                           'h': 0.8, 'Kcbini': 0.15, 'Kcbmid': 1.10, 
                           'Kcbend': 1.05, 'Zrmax': 0.5, 'p': 0.45}, 
      'Fababean (Dry)': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 0.3,
                         'h': 0.8, 'Kcbini': 0.15, 'Kcbmid': 1.10, 
                         'Kcbend': 0.2, 'Zrmax': 0.5, 'p': 0.45}, 
      'Grabanzo': {'Kcini': 0.4, 'Kcmid': 1.15, 'Kcend': 0.35, 'h': 0.8,
                   'Kcbini': 0.15, 'Kcbmid': 1.05, 'Kcbend': 0.25, 
                   'Zrmax': 0.6, 'p': 0.45}, 
      'Green Gram and Cowpeas (Fresh)': {'Kcini': 0.4, 'Kcmid': 1.05,
                                         'Kcend': 0.6, 'h': 0.4, 
                                         'Kcbini': 0.15, 'Kcbmid': 1.0, 
                                         'Kcbend': 0.55, 'Zrmax': 0.6, 
                                         'p': 0.45}, 
      'Green Gram and Cowpeas (Dry)': {'Kcini': 0.4, 'Kcmid': 1.05,
                                       'Kcend': 0.35, 'h': 1.4, 
                                       'Kcbini': 0.15, 'Kcbmid': 1.0, 
                                       'Kcbend': 0.25, 'Zrmax': 0.6, 
                                       'p': 0.45}, 
      'Groundnut (Peanut)': {'Kcini': 0.4, 'Kcmid': 1.15, 'Kcend': 0.6, 
                             'h': 0.4, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                             'Kcbend': 0.5, 'Zrmax': 0.5, 'p': 0.5}, 
      'Lentil': {'Kcini': 0.4, 'Kcmid': 1.1, 'Kcend': 0.3, 'h': 0.5,
                 'Kcbini': 0.15, 'Kcbmid': 1.05, 'Kcbend': 0.2, 
                 'Zrmax': 0.6, 'p': 0.5}, 
      'Peas (Fresh)': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 1.1, 
                       'h': 0.5, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                       'Kcbend': 1.05, 'Zrmax': 0.6, 'p': 0.35}, 
      'Peas (Dry)': {'Kcini': 0.5, 'Kcmid': 1.15, 'Kcend': 0.3,
                     'h': 0.5, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                     'Kcbend': 0.2, 'Zrmax': 0.6, 'p': 0.4}, 
      'Soybeans': {'Kcini': 0.4, 'Kcmid': 1.15, 'Kcend': 0.5, 'h': 0.5,
                   'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.3, 
                   'Zrmax': 0.6, 'p': 0.5}, 
      'Artichokes': {'Kcini': 0.5, 'Kcmid': 1, 'Kcend': 0.95, 'h': 0.7,
                     'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.9, 
                     'Zrmax': 0.6, 'p': 0.45}, 
      'Asparagus': {'Kcini': 0.5, 'Kcmid': 0.95, 'Kcend': 0.3, 'h': 0.2,
                    'Kcbini': 0.15, 'Kcbmid': 0.9, 'Kcbend': 0.2, 
                    'Zrmax': 1.2, 'p': 0.45}, 
      'Mint': {'Kcini': 0.6, 'Kcmid': 1.15, 'Kcend': 1.1, 'h': 0.6,
               'Kcbini': 0.4, 'Kcbmid': 1.1, 'Kcbend': 1.05, 
               'Zrmax': 0.4, 'p': 0.4}, 
      'Strawberries': {'Kcini': 0.4, 'Kcmid': 0.85, 'Kcend': 0.75, 
                       'h': 0.2, 'Kcbini': 0.3, 'Kcbmid': 0.8, 
                       'Kcbend': 0.7, 'Zrmax': 0.2, 'p': 0.2}, 
      'Cotton': {'Kcini': 0.35, 'Kcmid': 1.15, 'Kcend': 0.7, 'h': 1.2, 
                 'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.5, 
                 'Zrmax': 1.0, 'p': 0.65}, 
      'Flax': {'Kcini': 0.35, 'Kcmid': 1.1, 'Kcend': 0.25, 'h': 1.2,
               'Kcbini': 0.15, 'Kcbmid': 1.05, 'Kcbend': 0.2, 
               'Zrmax': 1.0, 'p': 0.5}, 
      'Sisal': {'Kcini': 0.35, 'Kcmid': 0.4, 'Kcend': 0.4, 'h': 1.5,
                'Kcbini': 0.15, 'Kcbmid': 0.4, 'Kcbend': 0.4, 
                'Zrmax': 0.5, 'p': 0.8}, 
      'Castorbean (Ricinus)': {'Kcini': 0.35, 'Kcmid': 1.15,
                               'Kcend': 0.55, 'h': 0.3, 'Kcbini': 0.15, 
                               'Kcbmid': 1.1, 'Kcbend': 0.45, 
                               'Zrmax': 1.0, 'p': 0.5}, 
      'Rapeseed, Canola': {'Kcini': 0.35, 'Kcmid': 1.15, 'Kcend': 0.35, 
                           'h': 0.6, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                           'Kcbend': 0.25, 'Zrmax': 1.0, 'p': 0.6}, 
      'Safflower': {'Kcini': 0.35, 'Kcmid': 1.15, 'Kcend': 0.25,
                    'h': 0.8, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                    'Kcbend': 0.2, 'Zrmax': 1.0, 'p': 0.6}, 
      'Sesame': {'Kcini': 0.35, 'Kcmid': 1.1, 'Kcend': 0.25, 'h': 1.0,
                 'Kcbini': 0.15, 'Kcbmid': 1.05, 'Kcbend': 0.2, 
                 'Zrmax': 1.0, 'p': 0.6}, 
      'Sunflower': {'Kcini': 0.35, 'Kcmid': 1.15, 'Kcend': 0.35,
                    'h': 2.0, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                    'Kcbend': 0.25, 'Zrmax': 0.8, 'p': 0.45}, 
      'Barley': {'Kcini': 0.3, 'Kcmid': 1.15, 'Kcend': 0.25, 'h': 1.0,
                 'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.15, 
                 'Zrmax': 1.0, 'p': 0.55}, 
      'Oats': {'Kcini': 0.3, 'Kcmid': 1.15, 'Kcend': 0.25, 'h': 1.0,
               'Kcbini': 0.15, 'Kcbmid': 1.1, 'Kcbend': 0.15, 
               'Zrmax': 1.0, 'p': 0.55}, 
      'Spring Wheat': {'Kcini': 0.3, 'Kcmid': 1.15, 'Kcend': 0.25,
                       'h': 1.0, 'Kcbini': 0.15, 'Kcbmid': 1.1, 
                       'Kcbend': 0.15, 'Zrmax': 1.0, 'p': 0.55}, 
      'Winter Wheat (Frozen Soils)': {'Kcini': 0.4, 'Kcmid': 1.15,
                                      'Kcend': 0.25, 'h': 1.0, 
                                      'Kcbini': 0.15, 'Kcbmid': 1.1, 
                                      'Kcbend': 0.15, 'Zrmax': 1.5, 
                                      'p': 0.55}, 
      'Winter Wheat (Non - Frozen Soils)': {'Kcini': 0.7, 'Kcmid': 1.15,
                                            'Kcend': 0.25, 'h': 1.0, 
                                            'Kcbini': 0.15, 
                                            'Kcbmid': 1.1, 
                                            'Kcbend': 0.15, 
                                            'Zrmax': 1.5,'p': 0.55}, 
      'Maize, Field (grain)': {'Kcini': 0.3, 'Kcmid': 1.2,
                               'Kcend': 0.6, 'h': 2.0, 'Kcbini': 0.15, 
                               'Kcbmid': 1.15, 'Kcbend': 0.5, 
                               'Zrmax': 1.0, 'p': 0.55}, 
      'Maize, Sweet (sweet corn)': {'Kcini': 0.3, 'Kcmid': 1.15,
                                    'Kcend': 1.05, 'h': 1.5, 
                                    'Kcbini': 0.15, 'Kcbmid': 1.1, 
                                    'Kcbend': 1.0, 'Zrmax': 0.8, 
                                    'p': 0.5}, 
      'Millet': {'Kcini': 0.3, 'Kcmid': 1, 'Kcend': 0.3, 'h': 1.5,
                 'Kcbini': 0.15, 'Kcbmid': 0.95, 'Kcbend': 0.2, 
                 'Zrmax': 1.0, 'p': 0.55}, 
      'Sorghum (Grain)': {'Kcini': 0.3, 'Kcmid': 1, 'Kcend': 0.55,
                          'h': 1.0, 'Kcbini': 0.15, 'Kcbmid': 0.95, 
                          'Kcbend': 0.35, 'Zrmax': 1.0, 'p': 0.55}, 
      'Sorghum (Sweet)': {'Kcini': 0.3, 'Kcmid': 1.2, 'Kcend': 1.05, 
                          'h': 2.0, 'Kcbini': 0.15, 'Kcbmid': 1.15, 
                          'Kcbend': 1.0, 'Zrmax': 1.0, 'p': 0.5}, 
      'Rice': {'Kcini': 1.05, 'Kcmid': 1.2, 'Kcend': 0.9, 'h': 1.0,
               'Kcbini': 1.0, 'Kcbmid': 1.15, 'Kcbend': 0.7, 
               'Zrmax': 0.5, 'p': 0.2}, 
      'Alfalfa Hay': {'Kcini': 0.4, 'Kcmid': 0.95, 'Kcend': 0.9,
                      'h': 0.7, 'Kcbini': 0.3, 'Kcbmid': 1.15, 
                      'Kcbend': 1.1, 'Zrmax': 1.0, 'p': 0.55}, 
      'Alfalfa Hay (seed)': {'Kcini': 0.4, 'Kcmid': 0.5, 'Kcend': 0.5, 
                             'h': 0.7, 'Kcbini': 0.3, 'Kcbmid': 0.45, 
                             'Kcbend': 0.45, 'Zrmax': 1.0, 'p': 0.6}, 
      'Bermuda hay': {'Kcini': 0.55, 'Kcmid': 1.00, 'Kcend': 0.85, 
                      'h': 0.35, 'Kcbini': 0.5, 'Kcbmid': 0.95, 
                      'Kcbend': 0.8, 'Zrmax': 1.0, 'p': 0.55}, 
      'Bermuda hay (seed)': {'Kcini': 0.35, 'Kcmid': 0.9,
                             'Kcend': 0.65, 'h': 0.4, 'Kcbini': 0.15, 
                             'Kcbmid': 0.85, 'Kcbend': 0.6, 
                             'Zrmax': 1.0, 'p': 0.6}, 
      'Clover hay, Berseem': {'Kcini': 0.4, 'Kcmid': 0.90,
                              'Kcend': 0.85, 'h': 0.6, 'Kcbini': 0.3, 
                              'Kcbmid': 1.1, 'Kcbend': 1.05, 
                              'Zrmax': 0.6, 'p': 0.5}, 
      'Rye Grass hay': {'Kcini': 0.95, 'Kcmid': 1.05, 'Kcend': 1.0,
                        'h': 0.3, 'Kcbini': 0.85, 'Kcbmid': 1.0, 
                        'Kcbend': 0.95, 'Zrmax': 0.6,'p': 0.6}, 
      'Sudan Grass hay (annual)': {'Kcini': 0.5, 'Kcmid': 0.90, 
                                    'Kcend': 0.85, 'h': 1.2, 
                                    'Kcbini': 0.3, 'Kcbmid': 1.1, 
                                    'Kcbend': 1.05, 'Zrmax': 1.0, 
                                    'p': 0.55}, 
      'Grazing Pasture (Rotated)': {'Kcini': 0.4, 'Kcmid': 0.85, 
                                    'Kcend': 0.85, 'h': 0.15, 
                                    'Kcbini': 0.3, 'Kcbmid': 0.8, 
                                    'Kcbend': 0.8, 'Zrmax': 0.5, 
                                    'p': 0.6}, 
      'Grazing Pasture': {'Kcini': 0.3, 'Kcmid': 0.75, 'Kcend': 0.75, 
                          'h': 0.1, 'Kcbini': 0.3, 'Kcbmid': 0.7, 
                          'Kcbend': 0.7,'Zrmax': 0.5, 'p': 0.6}, 
      'Turf grass (cool season)': {'Kcini': 0.9, 'Kcmid': 0.95, 
                                    'Kcend': 0.95, 'h': 0.1, 
                                    'Kcbini': 0.85, 'Kcbmid': 0.9, 
                                    'Kcbend': 0.9, 'Zrmax': 0.5, 
                                    'p': 0.4}, 
      'Turf grass (warm season)': {'Kcini': 0.8, 'Kcmid': 0.85, 
                                    'Kcend': 0.85, 'h': 0.1, 
                                    'Kcbini': 0.75, 'Kcbmid': 0.8, 
                                    'Kcbend': 0.8, 'Zrmax': 0.5, 
                                    'p': 0.5}, 
      'Sugar Cane': {'Kcini': 0.4, 'Kcmid': 1.25, 'Kcend': 0.75, 
                      'h': 3.0, 'Kcbini': 0.15, 'Kcbmid': 1.2, 
                      'Kcbend': 0.7, 'Zrmax': 1.2, 'p': 0.65}, 
      'Banana (1st year)': {'Kcini': 0.5, 'Kcmid': 1.1, 'Kcend': 1.0, 
                            'h': 3.0, 'Kcbini': 0.15, 'Kcbmid': 1.05, 
                            'Kcbend': 0.9, 'Zrmax': 0.5, 'p': 0.35}, 
      'Banana (2nd year)': {'Kcini': 1.0, 'Kcmid': 1.2, 'Kcend': 1.1, 
                            'h': 4.0, 'Kcbini': 0.6, 'Kcbmid': 1.1, 
                            'Kcbend': 1.05, 'Zrmax': 0.5, 'p': 0.35}, 
      'Cacao': {'Kcini': 1.0, 'Kcmid': 1.05, 'Kcend': 1.05, 'h': 3.0, 
                'Kcbini': 0.9, 'Kcbmid': 1.0, 'Kcbend': 1.0, 
                'Zrmax': 0.7, 'p': 0.3}, 
      'Coffee': {'Kcini': 1.05, 'Kcmid': 1.1, 'Kcend': 1.1, 'h': 2.0, 
                  'Kcbini': 1.0, 'Kcbmid': 1.05, 'Kcbend': 1.05, 
                  'Zrmax': 0.9, 'p': 0.4}, 
      'Date Palms': {'Kcini': 0.9, 'Kcmid': 0.95, 'Kcend': 0.95, 
                      'h': 8.0, 'Kcbini': 0.8, 'Kcbmid': 0.85, 
                      'Kcbend': 0.85, 'Zrmax': 1.5, 'p': 0.5}, 
      'Palm Trees': {'Kcini': 0.95, 'Kcmid': 1, 'Kcend': 1.0, 'h': 8.0, 
                      'Kcbini': 0.85, 'Kcbmid': 0.9, 'Kcbend': 0.9, 
                      'Zrmax': 0.7, 'p': 0.65}, 
      'Pineapple': {'Kcini': 0.5, 'Kcmid': 0.5, 'Kcend': 0.5, 'h': 0.6, 
                    'Kcbini': 0.3, 'Kcbmid': 0.45, 'Kcbend': 0.45, 
                    'Zrmax': 0.3,'p': 0.5}, 
      'Rubber Trees': {'Kcini': 0.95, 'Kcmid': 1, 'Kcend': 1.0, 
                        'h': 10.0, 'Kcbini': 0.85, 'Kcbmid': 0.9, 
                        'Kcbend': 0.9, 'Zrmax': 1.0, 'p': 0.4}, 
      'Tea': {'Kcini': 0.95, 'Kcmid': 1, 'Kcend': 1.0, 'h': 1.5, 
              'Kcbini': 0.9,'Kcbmid': 0.95, 'Kcbend': 0.9, 
              'Zrmax': 0.9, 'p': 0.4}, 
      'Berries (bushes)': {'Kcini': 0.3, 'Kcmid': 1.05, 'Kcend': 0.5, 
                            'h': 1.5, 'Kcbini': 0.2, 'Kcbmid': 1.0, 
                            'Kcbend': 0.4, 'Zrmax': 0.6, 'p': 0.5}, 
      'Grapes (Table or Raisin)': {'Kcini': 0.3, 'Kcmid': 0.85, 
                                    'Kcend': 0.45, 'h': 2.0, 
                                    'Kcbini': 0.15, 'Kcbmid': 0.8, 
                                    'Kcbend': 0.4, 'Zrmax': 1.0, 
                                    'p': 0.35}, 
      'Grapes (Wine)': {'Kcini': 0.3, 'Kcmid': 0.7, 'Kcend': 0.45, 
                        'h': 1.5, 'Kcbini': 0.15, 'Kcbmid': 0.65, 
                        'Kcbend': 0.4, 'Zrmax': 1.0, 'p': 0.45}, 
      'Hops': {'Kcini': 0.3, 'Kcmid': 1.05, 'Kcend': 0.85, 'h': 5.0, 
                'Kcbini': 0.15, 'Kcbmid': 1.0, 'Kcbend': 0.8, 
                'Zrmax': 1.0, 'p': 0.5}, 
      'Almonds': {'Kcini': 0.4, 'Kcmid': 0.9, 'Kcend': 0.65, 'h': 5.0, 
                  'Kcbini': 0.2, 'Kcbmid': 0.85, 'Kcbend': 0.6,
                  'Zrmax': 1.0, 'p': 0.4}, 
      'Apples, Cherries, Pears': {'Kcini': 0.8, 'Kcmid': 1.2, 
                                  'Kcend': 0.85, 'h': 4.0, 
                                  'Kcbini': 0.75, 'Kcbmid': 1.15, 
                                  'Kcbend': 0.8, 'Zrmax': 1.0, 
                                  'p': 0.5}, 
      'Apricots, Peaches, Stone Fruit': {'Kcini': 0.8, 'Kcmid': 1.15, 
                                          'Kcend': 0.85, 'h': 3.0, 
                                          'Kcbini': 0.75, 'Kcbmid': 1.1, 
                                          'Kcbend': 0.8, 'Zrmax': 1.0, 
                                          'p': 0.5}, 
      'Avocado': {'Kcini': 0.6, 'Kcmid': 0.85, 'Kcend': 0.75, 'h': 3.0, 
                  'Kcbini': 0.5, 'Kcbmid': 0.8, 'Kcbend': 0.7, 
                  'Zrmax': 0.5, 'p': 0.7}, 
      'Citrus': {'Kcini': 0.75, 'Kcmid': 0.7, 'Kcend': 0.75, 'h': 4.0, 
                  'Kcbini': 0.75, 'Kcbmid': 0.7, 'Kcbend': 0.75, 
                  'Zrmax': 1.2, 'p': 0.5}, 
      'Conifer Trees': {'Kcini': 1.0, 'Kcmid': 1, 'Kcend': 1.0, 
                        'h': 10.0, 'Kcbini': 0.95, 'Kcbmid': 0.95, 
                        'Kcbend': 0.95, 'Zrmax': 1.0, 'p': 0.7}, 
      'Kiwi': {'Kcini': 0.4, 'Kcmid': 1.05, 'Kcend': 1.05, 'h': 3.0, 
               'Kcbini': 0.2, 'Kcbmid': 1.0, 'Kcbend': 1.0, 
               'Zrmax': 0.7, 'p': 0.35}, 
      'Olives': {'Kcini': 0.65, 'Kcmid': 0.7, 'Kcend': 0.7, 'h': 3.0, 
                 'Kcbini': 0.55, 'Kcbmid': 0.65, 'Kcbend': 0.65, 
                 'Zrmax': 1.2, 'p': 0.65}, 
      'Pistachios': {'Kcini': 0.4, 'Kcmid': 1.1,'Kcend': 0.45, 
                     'h': 3.0, 'Kcbini': 0.2, 'Kcbmid': 1.05, 
                     'Kcbend': 0.4, 'Zrmax': 1.0, 'p': 0.4}, 
      'Walnut Orchard': {'Kcini': 0.5, 'Kcmid': 1.1, 'Kcend': 0.65, 
                         'h': 4.0, 'Kcbini': 0.4, 'Kcbmid': 1.05, 
                         'Kcbend': 0.6, 'Zrmax': 1.7, 'p': 0.5}}
    self.table11= {
      'Broccoli': {'Lini': 35, 'Ldev': 45, 'Lmid': 40, 'Llate': 15, 
                   'Total': 135},
      'Brussel Sprouts': {'Lini': 20, 'Ldev': 30, 'Lmid': 20, 
                          'Llate': 10, 'Total': 80}, 
      'Cabbage': {'Lini': 40, 'Ldev': 60, 'Lmid': 50, 'Llate': 15, 
                  'Total': 165}, 
      'Carrots': {'Lini': 30, 'Ldev': 50, 'Lmid': 90, 'Llate': 30, 
                  'Total': 200}, 
      'Cauliflower': {'Lini': 35, 'Ldev': 50, 'Lmid': 40, 'Llate': 15, 
                      'Total': 140}, 
      'Celery': {'Lini': 30, 'Ldev': 55, 'Lmid': 105, 'Llate': 20, 
                 'Total': 210}, 
      'Lettuce': {'Lini': 25, 'Ldev': 35, 'Lmid': 30, 'Llate': 10, 
                  'Total': 100}, 
      'Onions (dry)': {'Lini': 20, 'Ldev': 35, 'Lmid': 110, 'Llate': 45, 
                       'Total': 210}, 
      'Onions (green)': {'Lini': 30, 'Ldev': 55, 'Lmid': 55, 
                         'Llate': 40, 'Total': 180}, 
      'Onions (seed)': {'Lini': 20, 'Ldev': 45, 'Lmid': 165, 
                        'Llate': 45, 'Total': 275}, 
      'Spinach': {'Lini': 20, 'Ldev': 30, 'Lmid': 40, 'Llate': 10, 
                  'Total': 100}, 
      'Radish': {'Lini': 10, 'Ldev': 10, 'Lmid': 15, 'Llate': 5, 
                 'Total': 40}, 
      'Egg Plant': {'Lini': 30, 'Ldev': 40, 'Lmid': 40, 'Llate': 20, 
                    'Total': 130}, 
      'Sweet Peppers (bell)': {'Lini': 30, 'Ldev': 40, 'Lmid': 110, 
                               'Llate': 30, 'Total': 210}, 
      'Tomato': {'Lini': 35, 'Ldev': 40, 'Lmid': 50, 'Llate': 30, 
                 'Total': 155}, 
      'Cantaloupe': {'Lini': 30, 'Ldev': 45, 'Lmid': 35, 'Llate': 10, 
                     'Total': 120}, 
      'Cucumber (Fresh Market)': {'Lini': 20, 'Ldev': 30, 'Lmid': 40, 
                                  'Llate': 15, 'Total': 105}, 
      'Cucumber (Machine Harvest)': {'Lini': 20, 'Ldev': 30, 'Lmid': 40, 
                                     'Llate': 15, 'Total': 105}, 
      'Pumpkin, Winter Squash': {'Lini': 25, 'Ldev': 35, 'Lmid': 35, 
                                 'Llate': 25, 'Total': 120}, 
      'Squash, Zucchini': {'Lini': 25, 'Ldev': 35, 'Lmid': 25, 
                           'Llate': 15, 'Total': 100}, 
      'Sweet Melons': {'Lini': 30, 'Ldev': 30, 'Lmid': 50, 
                       'Llate': 30, 'Total': 140}, 
      'Watermelon': {'Lini': 20, 'Ldev': 30, 'Lmid': 30, 'Llate': 30, 
                     'Total': 110}, 
      'Beets, table': {'Lini': 25, 'Ldev': 30, 'Lmid': 25, 'Llate': 10, 
                       'Total': 90}, 
      'Cassava (year 1)': {'Lini': 20, 'Ldev': 40, 'Lmid': 90, 
                           'Llate': 60, 'Total': 210}, 
      'Cassava (year 2)': {'Lini': 150, 'Ldev': 40, 'Lmid': 110, 
                           'Llate': 60, 'Total': 360}, 
      'Potato': {'Lini': 45, 'Ldev': 30, 'Lmid': 70, 'Llate': 20, 
                 'Total': 165}, 
      'Sweet Potato': {'Lini': 20, 'Ldev': 30, 'Lmid': 60, 'Llate': 40, 
                       'Total': 150}, 
      'Sugar Beet': {'Lini': 50, 'Ldev': 40, 'Lmid': 50, 'Llate': 40, 
                     'Total': 180}, 
      'Beans, green': {'Lini': 15, 'Ldev': 25, 'Lmid': 25, 'Llate': 10,
                        'Total': 75}, 
      'Beans, dry and Pulses': {'Lini': 20, 'Ldev': 30, 'Lmid': 40, 
                                'Llate': 20, 'Total': 110}, 
      'Fababean (Fresh)': {'Lini': 15, 'Ldev': 25, 'Lmid': 35, 
                           'Llate': 15, 'Total': 90}, 
      'Fababean (Dry)': {'Lini': 15, 'Ldev': 25, 'Lmid': 35, 
                         'Llate': 15, 'Total': 90}, 
      'Green Gram and Cowpeas (Fresh)': {'Lini': 20, 'Ldev': 30, 
                                         'Lmid': 30, 'Llate': 20, 
                                         'Total': 110}, 
      'Green Gram and Cowpeas (Dry)': {'Lini': 20, 'Ldev': 30, 
                                       'Lmid': 30, 'Llate': 20, 
                                       'Total': 110}, 
      'Groundnut (Peanut)': {'Lini': 35, 'Ldev': 45, 'Lmid': 35, 
                             'Llate': 25, 'Total': 140}, 
      'Lentil': {'Lini': 25, 'Ldev': 35, 'Lmid': 70, 'Llate': 40, 
                 'Total': 170}, 
      'Peas (Fresh)': {'Lini': 35, 'Ldev': 25, 'Lmid': 30, 'Llate': 20, 
                       'Total': 110}, 
      'Peas (Dry)': {'Lini': 35, 'Ldev': 25, 'Lmid': 30, 'Llate': 20, 
                     'Total': 110}, 
      'Soybeans': {'Lini': 20, 'Ldev': 30, 'Lmid': 60, 'Llate': 25, 
                   'Total': 140}, 
      'Artichokes': {'Lini': 40, 'Ldev': 40, 'Lmid': 250, 'Llate': 30, 
                     'Total': 360}, 
      'Asparagus': {'Lini': 90, 'Ldev': 30, 'Lmid': 200, 'Llate': 45, 
                    'Total': 365}, 
      'Cotton': {'Lini': 30, 'Ldev': 50, 'Lmid': 55, 'Llate': 45, 
                 'Total': 180}, 
      'Flax': {'Lini': 30, 'Ldev': 40, 'Lmid': 100, 'Llate': 50, 
               'Total': 220}, 
      'Castorbean (Ricinus)': {'Lini': 25, 'Ldev': 40, 'Lmid': 65, 
                               'Llate': 50, 'Total': 180}, 
      'Safflower': {'Lini': 20, 'Ldev': 35, 'Lmid': 45, 'Llate': 25, 
                    'Total': 125}, 
      'Sesame': {'Lini': 20, 'Ldev': 30, 'Lmid': 40, 'Llate': 20, 
                 'Total': 100}, 
      'Sunflower': {'Lini': 25, 'Ldev': 35, 'Lmid': 45, 'Llate': 25, 
                    'Total': 130}, 
      'Barley': {'Lini': 20, 'Ldev': 25, 'Lmid': 60, 'Llate': 30, 
                 'Total': 135}, 
      'Oats': {'Lini': 20, 'Ldev': 25, 'Lmid': 60, 'Llate': 30, 
               'Total': 135}, 
      'Spring Wheat': {'Lini': 20, 'Ldev': 25, 'Lmid': 60, 'Llate': 30, 
                       'Total': 135}, 
      'Winter Wheat (Frozen Soils)': {'Lini': 160, 'Ldev': 75, 
                                      'Lmid': 75, 'Llate': 25, 
                                      'Total': 335}, 
      'Winter Wheat (Non - Frozen Soils)': {'Lini': 160, 'Ldev': 75, 
                                            'Lmid': 75, 'Llate': 25, 
                                            'Total': 335}, 
      'Maize, Field (grain)': {'Lini': 30, 'Ldev': 40, 'Lmid': 50, 
                               'Llate': 50, 'Total': 170}, 
      'Maize, Sweet(sweet corn)': {'Lini': 30, 'Ldev': 30, 'Lmid': 30, 
                                   'Llate': 10, 'Total': 110}, 
      'Millet': {'Lini': 20, 'Ldev': 30, 'Lmid': 55, 'Llate': 35, 
                 'Total': 140}, 
      'Sorghum (Grain)': {'Lini': 20, 'Ldev': 25, 'Lmid': 40, 
                          'Llate': 30, 'Total': 130}, 
      'Sorghum (Sweet)': {'Lini': 20, 'Ldev': 25, 'Lmid': 40, 
                          'Llate': 30, 'Total': 130}, 
      'Rice': {'Lini': 30, 'Ldev': 30, 'Lmid': 60, 'Llate': 30, 
               'Total': 150}, 
      'Alfalfa Hay': {'Lini': 5, 'Ldev': 20, 'Lmid': 10, 'Llate': 10, 
                      'Total': 45}, 
      'Alfalfa Hay (seed)': {'Lini': 5, 'Ldev': 20, 'Lmid': 10, 
                             'Llate': 10, 'Total': 45}, 
      'Bermuda hay': {'Lini': 10, 'Ldev': 15, 'Lmid': 75, 'Llate': 35, 
                      'Total': 135}, 
      'Bermuda hay (seed)': {'Lini': 10, 'Ldev': 25, 'Lmid': 35, 
                             'Llate': 35, 'Total': 105}, 
      'Sudan Grass hay (annual)': {'Lini': 3, 'Ldev': 15, 'Lmid': 12, 
                                   'Llate': 7, 'Total': 37}, 
      'Sugar Cane': {'Lini': 35, 'Ldev': 105, 'Lmid': 210, 'Llate': 70, 
                     'Total': 420}, 
      'Banana (1st year)': {'Lini': 120, 'Ldev': 90, 'Lmid': 120, 
                            'Llate': 60, 'Total': 390}, 
      'Banana (2nd year)': {'Lini': 120, 'Ldev': 60, 'Lmid': 180, 
                            'Llate': 5, 'Total': 365}, 
      'Pineapple': {'Lini': 60, 'Ldev': 120, 'Lmid': 600, 'Llate': 10, 
                    'Total': 790}, 
      'Grapes (Table or Raisin)': {'Lini': 20, 'Ldev': 50, 'Lmid': 75, 
                                   'Llate': 60, 'Total': 205}, 
      'Grapes (Wine)': {'Lini': 20, 'Ldev': 50, 'Lmid': 75, 'Llate': 60, 
                        'Total': 205}, 
      'Hops': {'Lini': 25, 'Ldev': 40, 'Lmid': 80, 'Llate': 10, 
               'Total': 155}, 
      'Apples, Cherries, Pears': {'Lini': 30, 'Ldev': 50, 'Lmid': 130, 
                                  'Llate': 30, 'Total': 240}, 
      'Apricots, Peaches, Stone Fruit': {'Lini': 30, 'Ldev': 50, 
                                         'Lmid': 130, 'Llate': 30, 
                                         'Total': 240}, 
      'Citrus': {'Lini': 60, 'Ldev': 90, 'Lmid': 120, 'Llate': 95, 
                 'Total': 365}, 
      'Olives': {'Lini': 30, 'Ldev': 90, 'Lmid': 60, 'Llate': 90, 
                 'Total': 270}, 
      'Pistachios': {'Lini': 20, 'Ldev': 60, 'Lmid': 30, 'Llate': 40, 
                     'Total': 150}, 
      'Walnut Orchard': {'Lini': 20, 'Ldev': 10, 'Lmid': 130, 
                         'Llate': 30, 'Total': 190}}
